---
- hosts: "{{ host_server }}"
  gather_facts: yes
  vars_files:
    - vars/global.yaml #AnsibaleTest/roles/restore_db/tasks/main.yml
  roles:
    - AnsibaleTest/roles/restore_db/tasks/main.yml
   # - { role: restore_db,
   #    tags: [ restore_db ] } 
